# Generated by Django 2.1 on 2019-09-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='page_number',
            field=models.IntegerField(verbose_name='Número da Página'),
        ),
    ]
