# Generated by Django 2.1 on 2019-09-30 12:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20190930_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo'),
        ),
    ]
