# Generated by Django 2.1 on 2019-09-30 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20190930_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
